name: "Hello Actions!"
description: "Greet Eduardo"
author: "geduardo"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "Eduardo"
    
runs:
    using: "docker"
    image: "Dockerfile"
    
branding:
    icon: "mic"
    color: "purple"
    
